name: Blogger Professional Bot

on:
  schedule:
    - cron: '0 */8 * * *' # النشر كل 8 سوايع أوتوماتيكياً
  workflow_dispatch: # تشغيل يدوي للتجربة من واجهة GitHub

jobs:
  post_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # زدنا requests و Pexels API محتاج ليها الكود دابا
        run: pip install groq requests

      - name: Run Auto Bot
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          BLOGGER_EMAIL: ${{ secrets.BLOGGER_EMAIL }}
          MY_GMAIL: ${{ secrets.MY_GMAIL }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }} # تأكد أنك زدتي هاد الساروت في Secrets
        run: python main.py
