name: Blogger Professional Bot

on:
  schedule:
    # سيتم تشغيل البوت كل 8 ساعات تلقائياً
    - cron: '0 */8 * * *' 
  workflow_dispatch: 

jobs:
  post_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install groq requests

      - name: Run Auto Bot
        env:
          # ربط السيكريت بالمتغيرات التي يطلبها الكود الجديد
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          BLOGGER_EMAIL: ${{ secrets.BLOGGER_EMAIL }}
          
          # لاحظ هنا استعملنا الأسماء الجديدة الموجودة في كود بايثون
          MY_GMAIL: ${{ secrets.GMAIL_SENDER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_SENDER_PASS }}
          
        run: python main.py
